version: "3.9"

services:
  web:
    build: .
    command: 'python manage.py main'
    volumes:
      - .:/code
    ports:
      - "8001:8000"


  djangoq:
    build: .
    command: python manage.py qcluster
    volumes:
      - .:/code
    ports:
      - "1616:1616"
